### ISSUE TITLE
ROUGE_L score

### ISSUE THREAD

**Issue by salvatoreferragamo** [TGoldsack1/Corpora_for_Lay_Summarisation#1]
I want to know how you calculate the ROUGE_L score ? why i calculate it lower than yours but the same ROUGE-1 and ROUGE-2 scores?
Can you share the ROUGE-L calculating method?

**Comment by TGoldsack1** [comment]
Hi! For how we calculate the ROUGE-L scores, you can refer to [this script](https://github.com/TGoldsack1/BioLaySumm2023-evaluation_scripts/blob/master/evaluate_st1.py) in a different repo.
Hope this helps.

**Comment by salvatoreferragamo** [comment]
thanks for your reply! It means a lot .
After careful watching your code in other repo. I successfully find the way to calculate it!
Thanks a lot and wish you a good day.
