### ISSUE TITLE
huggingface error 

### ISSUE THREAD

**Issue by enesdoruk** [TGoldsack1/Corpora_for_Lay_Summarisation#2]
NotADirectoryError: [Errno 20] Not a directory: '/home/.cache/huggingface/datasets/downloads/522757c004d3707aae2245df6a952a70e31d13211db54c19d3dae80c62661523/train.json'

datasets.builder.DatasetGenerationError: An error occurred while generating the dataset

**Comment by TGoldsack1** [comment]
Thanks for raising this! 

It looks like the download on HuggingFace was getting stuck at the ["Can't scan file for viruses" URL](https://drive.usercontent.google.com/download?id=1lZ6PCAtXvmGjRZyp3vQQCEgO_yerH62Q&export=download&authuser=1). I have just changed the URLs in the so they now bypass this, and the download seems to be working again.

Let me know if you have any further issues.

**Comment by enesdoruk** [comment]
thank you for quick response, it works.
